version: '3.8'
services:
  mysql-container:
    image: mysql
    volumes:
      - ../../../inventory-data/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: chen
    restart: always
    networks:
      - common-network
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10

  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      mysql-container:
        condition: service_healthy # 增加健康检查
    restart: always
    ports:
      - 3005:3005
    networks:
      - common-network
    environment:
      DATABASE_URL: mysql://root:chen@mysql-container:3306/inventory

  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../../../inventory-data/minio-data:/var/lib/mysql
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: chenzeqi
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
